// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
    'aws_app_analytics': 'enable',
    'aws_cognito_identity_pool_id': 'us-west-2:19a62a70-f4c5-4fa3-b272-8ba6c9d7da05',
    'aws_cognito_region': 'us-west-2',
    'aws_content_delivery': 'enable',
    'aws_content_delivery_bucket': 'btdt-hosting-mobilehub-595402414',
    'aws_content_delivery_bucket_region': 'us-west-2',
    'aws_content_delivery_cloudfront': 'enable',
    'aws_content_delivery_cloudfront_domain': 'dggyyh1kahty1.cloudfront.net',
    'aws_dynamodb': 'enable',
    'aws_dynamodb_all_tables_region': 'us-west-2',
    'aws_dynamodb_table_schemas': [{"tableName":"btdt-mobilehub-595402414-AWSMobileTable","attributes":[{"name":"teamId","type":"S"},{"name":"personId","type":"S"},{"name":"email","type":"S"},{"name":"personName","type":"S"},{"name":"phone","type":"S"}],"indexes":[{"indexName":"personName-index","hashKey":"teamId","rangeKey":"personName"}],"region":"us-west-2","hashKey":"teamId","rangeKey":"personId"},{"tableName":"btdt-mobilehub-595402414-Deliveries","attributes":[{"name":"userId","type":"S"},{"name":"deliveryId","type":"S"},{"name":"address","type":"S"},{"name":"created","type":"N"},{"name":"latlng","type":"S"},{"name":"name","type":"S"}],"indexes":[],"region":"us-west-2","hashKey":"userId","rangeKey":"deliveryId"}],
    'aws_mobile_analytics_app_id': 'e586959399ea4872b357f317889fa8ba',
    'aws_mobile_analytics_app_region': 'us-east-1',
    'aws_project_id': '3bfaa542-1183-11e8-b7ec-1579a7b87ac8',
    'aws_project_name': 'btdt',
    'aws_project_region': 'us-west-2',
    'aws_resource_name_prefix': 'btdt-mobilehub-595402414',
    'aws_sign_in_enabled': 'enable',
    'aws_user_files': 'enable',
    'aws_user_files_s3_bucket': 'btdt-userfiles-mobilehub-595402414',
    'aws_user_files_s3_bucket_region': 'us-west-2',
    'aws_user_pools': 'enable',
    'aws_user_pools_id': 'us-west-2_O6lqLhH8W',
    'aws_user_pools_mfa_type': 'ON',
    'aws_user_pools_web_client_id': '5e8qrh99orl0qqmkkillbho2ek',
}

export default awsmobile;
